enum MostlyWhite {
	VAN = 'VAN',
	ONEEAR = 'ONEEAR',
	LIGHTSONG = 'LIGHTSONG',
	TAIL = 'TAIL',
	HEART = 'HEART',
	MOORISH = 'MOORISH',
	APRON = 'APRON',
	CAPSADDLE = 'CAPSADDLE',
	CHESTSPECK = 'CHESTSPECK',
	BLACKSTAR = 'BLACKSTAR',
	PETAL = 'PETAL',
	HEARTTWO = 'HEARTTWO',
	PEBBLESHINE = 'PEBBLESHINE',
	BOOTS = 'BOOTS',
	COW = 'COW',
	COWTWO = 'COWTWO',
	LOVEBUG = 'LOVEBUG',
	SHOOTINGSTAR = 'SHOOTINGSTAR',
	EYESPOT = 'EYESPOT',
	PEBBLE = 'PEBBLE',
	TAILTWO = 'TAILTWO',
	BUDDY = 'BUDDY',
	KROPKA = 'KROPKA'
}

export default MostlyWhite;
