enum Vit {
	VITILIGO = 'VITILIGO',
	VITILIGOTWO = 'VITILIGOTWO',
	MOON = 'MOON',
	PHANTOM = 'PHANTOM',
	KARPATI = 'KARPATI',
	POWDER = 'POWDER',
	BLEACHED = 'BLEACHED',
	SMOKEY = 'SMOKEY'
}

export default Vit;
